### ISSUE TITLE
[neat.css]Chrome 中 input,button 默认有 padding

### ISSUE THREAD

**Issue by yisibl** [thx/cube#20]
考虑去除默认的 padding 

``` css
input[type="button"], input[type="submit"], input[type="reset"], input[type="file"]::-webkit-file-upload-button, button {
  padding: 1px 6px;
}
```
