### ISSUE TITLE
裁剪方式隐藏元素是不是可以舍弃了？

### ISSUE THREAD

**Issue by huanglong-zz** [thx/cube#9]
- IE6-8 有严重漏洞
- VoiceOver 无法读出宽高为 0 的元素

既然有以上问题，尤其是第一条，那么这个 我们是不是可以不必写到样式库里面去，而作为一个 群博 或者 doc 记录即可。

``` css
.clip-hide {
    position: absolute !important; /*clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
    clip: rect(1px, 1px, 1px, 1px); /* 1 */
    padding: 0 !important;
    border: 0 none!important;
    height: 1px !important; /* 2 */
    width: 1px !important;
    overflow: hidden;
}
```
